{% set name = "swifter" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/swifter-{{ version }}.tar.gz
  sha256: e1bb74476a21b3f07a17aa18c97fdcba8599726bd17da732f09dabcc50e26ba0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - dask >=2.10.0
    - pandas >=1.0.0
    - psutil >=5.6.6
    - python >={{ python_min }}
    - tqdm >=4.33.0
  run_constrained:
    - ray >=1.0.0
    - ipywidgets >=7.0.0

test:
  imports:
    - swifter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jmcarpenter2/swifter
  summary: A package which efficiently applies any function to a pandas dataframe or series in the fastest available manner
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmcarpenter2
    - apcamargo
